jQuery(function(){function l(h){var c=jQuery(window).scrollTop(),e=c+jQuery(window).height(),g=jQuery(h).offset().top;return g+jQuery(h).height()<=e&&g>=c}var e=jQuery("#cfgen-form-3");if(!jQuery.isFunction(jQuery.fn.on)){var q="The form requires at least jQuery 1.7.2 to work properly.<br>jQuery "+jQuery().jquery+" has been loaded instead.";e.prepend('<p style="background-color:#FF0000; color:#fff; font-family:Verdana; Arial; font-size:12px; padding:4px; ">'+q+"</p>")}e.find(".cfgen-uploadfilename").val("");
e.on("click","img.cfgen-captcha-refresh",function(){e.find("img.cfgen-captcha-img").prop("src","cfgen-form-3/inc/captcha.php?r="+Math.random())});e.on("click",'input[type="submit"].cfgen-submit',function(){var h=jQuery(this);h.hide();var c=h.closest("div.cfgen-form-container"),e=c.find("div.cfgen-loading");e.show();c.find("div.cfgen-errormessage").hide().remove();var g=[],m=[],k={};c.find(".cfgen-form-value").each(function(){var b=jQuery(this),d=b.closest("div.cfgen-e-c"),f=d.find(".cfgen-label-value"),
c=f.html();c||(c=b.prop("placeholder"));var a={};a.elementlabel_id=f.closest("label").prop("id");a.elementlabel_value=c;a.element_value="";b.is('input[type="radio"]')&&(a.element_type="radio");b.is('input[type="checkbox"]')&&(a.element_type="checkbox");b.hasClass("cfgen-type-selectmultiple")&&(a.element_type="selectmultiple");b.hasClass("cfgen-uploadfilename")&&(a.element_type="upload");b.hasClass("cfgen-type-date")&&(a.element_type="date");b.hasClass("cfgen-rating-c")&&(a.element_type="rating");
b.hasClass("cfgen-type-terms")&&(a.element_type="terms");"terms"===a.element_type&&(a.elementlabel_id=d.find("div.cfgen-e-set").prop("id"),a.elementlabel_value=d.find("label").text(),d.find('input[type="checkbox"]:checked').length&&(a.element_value="Checked"),a.element_id=b.prop("id"),g.push(a));"rating"===a.element_type&&(c=b.find(".fa"),f=c.filter(".cfgen-rating-selected").length,c=c.length,f=(f=0===f?"":f)?f+("/"+c):"",a.element_id=b.prop("id"),a.element_value=f,g.push(a));"upload"===a.element_type&&
(a.element_id=b.prop("name"),a.element_value=jQuery.trim(b.val()),f=b.closest("div.cfgen-input-group").find(".cfgen-uploaddeletefile").val(),jQuery.extend(a,{deletefile:f}),g.push(a));b.is(".cfgen-type-text, .cfgen-type-email, .cfgen-type-date, .cfgen-type-url, .cfgen-type-textarea, .cfgen-type-select, .cfgen-type-hidden")&&(a.element_id=b.prop("id"),a.element_value=b.val(),g.push(a));-1!=jQuery.inArray(a.element_type,["radio","checkbox","selectmultiple"])&&(a.element_id=b.prop("name"),k.hasOwnProperty(a.element_id)||
(k[a.element_id]=!0));if("radio"===a.element_type||"checkbox"===a.element_type)a.element_value=b.val(),b.is(":checked")&&a.element_value&&(k[a.element_id]=!1,g.push(a)),b.is(d.find("input[name="+a.element_id+"]:last"))&&k[a.element_id]&&(a.element_value="",g.push(a));"selectmultiple"===a.element_type&&(b.find("option:selected").each(function(){var b=jQuery(this);a.element_value=b.val();a.element_value&&(k[a.element_id]=!1,b=jQuery.extend({},a,{element_type:"selectmultiple"}),g.push(b))}),k[a.element_id]&&
g.push(a));b.hasClass("cfgen-type-time")&&(b=d.find("select.cfgen-time-hour"),f=d.find("select.cfgen-time-minute"),d=d.find("select.cfgen-time-ampm").val(),void 0==d&&(d=""),a.element_id=b.prop("name"),a.element_value=b.val()+":"+f.val()+" "+d,g.push(a))});c.find(".cfgen-deleteuploadedfile").each(function(){m.push(jQuery(this).val())});var n="",p="";c.find("img.cfgen-captcha-img").length&&(n=1,p=c.find('input[type="text"].cfgen-captcha-input').val());jQuery.post("cfgen-form-3/inc/form-validation.php",
{captcha_img:n,captcha_input:p,form_values:g,screen_width:screen.width,screen_height:screen.height,deleteuploadedfile:m},function(b){var d=jQuery.parseJSON(b);if("ok"===d.status)if(d.redirect_url)window.location.href=d.redirect_url;else{e.hide();var f=c.find(".cfgen-e-c");f.each(function(){jQuery(this).slideUp("fast",function(){--f.length||(l(".cfgen-form-container")||jQuery("html, body").animate({scrollTop:c.offset().top},"fast"),jQuery('<div class="cfgen-validationmessage">'+d.message+"</div>").appendTo(c.find(".cfgen-form-content")))})})}else{e.hide();
h.show();for(b=0;b<d.message.length;b++){var g=jQuery("[name="+d.message[b].element_id+"], [id="+d.message[b].element_id+"]").first().closest("div.cfgen-e-set");jQuery('<div class="cfgen-errormessage"></div>').text(d.message[b].errormessage).prependTo(g).fadeIn()}l("#"+d.message[0].elementlabel_id)||jQuery("html, body").animate({scrollTop:jQuery("#"+d.message[0].elementlabel_id).offset().top},"fast")}})});if(e.find(".cfgen-uploadfilename").length)e.on("click",".cfgen-deleteupload",function(){var e=
jQuery(this),c=e.closest("div.cfgen-uploadsuccess-c"),l=c.find(".cfgen-deleteupload-filename").val(),e=e.closest("div.cfgen-input-group");e.append('<input value="'+l+'" type="hidden" class="cfgen-deleteuploadedfile" />');e.find(".cfgen-uploadfilename").val("");c.remove()})});
